service: prisma-lambda-4-7-1
plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin

provider:
  name: aws
  region: us-west-2
  runtime: nodejs16.x

functions:
  listPosts:
    handler: index.handler
    events:
      - http:
          method: GET
          path: /

package:
  individually: true
  patterns:
    - "node_modules/.prisma/client/schema.prisma"
    - "node_modules/.prisma/client/libquery_engine-rhel-*"
